### ISSUE TITLE
encrypt sub-command broken by commit 1766cf5 (IDFGH-14062)

### ISSUE THREAD

**Issue by dan-powerverse** [espressif/esp-idf-nvs-partition-gen#10]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [X] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [X] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

Prior to commit 1766cf5, the `encrypt` command below works as expected and produces the output below.

```
python /opt/esp/esp-idf/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py encrypt --inputkey nvs_key.bin /tmp/nvs_partition.csv /tmp/nvs_partition.bin 0x4000

Creating NVS binary with version: V2 - Multipage Blob Support Enabled

Attempting to open:  /tmp/nvs_partition.csv

Created NVS binary: ===> /tmp/nvs_partition.bin

```

### Actual behavior (suspected bug)

Now, the command above fails (see terminal output below).

It is taking the first character of the .csv input filename (`/` in the example above) and trying to open that as a file.

### Error logs or terminal output

```shell
Creating NVS binary with version: V2 - Multipage Blob Support Enabled
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/esp/espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_nvs_partition_gen/__main__.py", line 4, in <module>
    main()
  File "/opt/esp/espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_nvs_partition_gen/nvs_partition_gen.py", line 1203, in main
    args.func(args)
  File "/opt/esp/espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_nvs_partition_gen/nvs_partition_gen.py", line 832, in encrypt
    generate(args, is_encr_enabled=True, encr_key=key)
  File "/opt/esp/espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_nvs_partition_gen/nvs_partition_gen.py", line 1050, in generate
    with open(i, 'rt', encoding='utf8') as input_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/'

```
```


### Steps to reproduce the behavior

```
source /opt/esp/esp-idf/export.sh

cat <<EOF > /tmp/nvs_partition.csv
 key,type,encoding,value
ems,namespace,,
wifi_ssid,data,string,testSSID-node5
wifi_psk,data,string,u+zQMS88L2qhMEN5Ldv1zQ==
EOF

python /opt/esp/esp-idf/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py encrypt --inputkey nvs_key.bin /tmp/nvs_partition.csv /tmp/nvs_partition.bin 0x4000
```

### Project release version

latest

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Linux

### Operating system version

Ubuntu 24.04

### Shell

Bash

### Additional context

Commit 1766cf5 changed the args handling in the `generate` sub-command to assume a list of input files rather than a single file, and changed the `argparse` options accordingly for that sub-command:

https://github.com/espressif/esp-idf-nvs-partition-gen/blob/a294bff1ab7384c3581eef468b5a1fabe14bf864/esp_idf_nvs_partition_gen/nvs_partition_gen.py#L1086

However, the `encrypt` sub-command also passes its args list through to the `generate()` function, but its `argparse` options were not updated so it still assumes a single `input` arg.  This is passed through as a string to the `generate()` function which assumes it is a list and just iterates through the string character-by-character.

The following patch resolves the issue.  I'll create a PR for this shortly:

```
diff --git a/esp_idf_nvs_partition_gen/nvs_partition_gen.py b/esp_idf_nvs_partition_gen/nvs_partition_gen.py
index 649bbd5..8012a39 100755
--- a/esp_idf_nvs_partition_gen/nvs_partition_gen.py
+++ b/esp_idf_nvs_partition_gen/nvs_partition_gen.py
@@ -1135,6 +1135,7 @@ def main():
     parser_encr.set_defaults(func=encrypt)
     parser_encr.add_argument('input',
                              default=None,
+                             nargs='+',
                              help=desc_format('Path to CSV file to parse'))
     parser_encr.add_argument('output',
                              default=None,

```

**Comment by adokitkat** [comment]
Fixed in cc6a9f5201fa206e5fd3e7e28e1ac9db1c188d06
